export default {
  user:{
    signUp:{
      name:'user.signUp',
      method:'POST',
      url:'/register'
    },
    login:{
      name:'user.login',
      method:'POST',
      url:'/login'
    },
    resetPassword:{
      name:'user.resetPassword',
      method:'POST',
      url:'/reset-password'
    }
  }
}