export default {
  user:{
    signUp:{
      name:'user.signUp',
      method:'POST',
      url:'/register'
    },
    login:{
      name:'user.login',
      method:'POST',
      url:'/login'
    },
    resetPassword:{
      name:'user.resetPassword',
      method:'POST',
      url:'/reset-password'
    },
    editPassword:{
      name:'user.editPassword',
      method:'PUT',
      url:'/edit-password'
    },
    editMail:{
      name:'user.editMail',
      method:'PUT',
      url:'/edit-mail'
    },
    editUsername:{
      name:'user.editUsername',
      method:'PUT',
      url:'/edit-username'
    }
  }
}